trigger:
- cvss4

pool:
  name: Default  # self-hosted agent pool
  demands:
    - Agent.Name -equals report

steps:
- script: |
    echo "Docker komutları:"
    docker --version
    docker compose version
  displayName: "Check Docker"

- script: |
    cd $(Build.SourcesDirectory)

    echo "Containerlari kapatiliyor..."
    docker compose down || true

    echo "Yeni build yapiliyor..."
    docker compose build

    echo "Uygulama kaldiriliyor..."
    docker compose up -d
  displayName: "Build & Deploy on Ubuntu Server"
